server:
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "738f4a9524c183bb80c161d4094e03c3"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    youtubeSearchLimit: 10
    soundcloudSearchLimit: 10
    gc-warnings: true
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - MWEB
      - TVHTML5EMBEDDED
      - ANDROID_VR
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
logging:
  file:
    path: ./logs/lavalink.log
  level:
    root: INFO
    lavalink: INFO
  request:
    enabled: true
    includeHeaders: false
    includePayload: true
    includeQueryString: true
